AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Deliforce web Backend'
Globals:
 Function:
   Environment:
     Variables:
       bucketName: llmbdaconstant
       constantFileName: constant.json
Resources:
 DeliforceanalyticdriverloggetMethodone:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: nnnna
      Timeout: 900
      MemorySize: 3008
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: ./index1.zip
      Policies: AWSLambdaFullAccess
      Role: arn:aws:iam::641553134660:role/service-role/demo1
 DeliforceanalyticdriverloggetMethodtwo:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: nnnnnb
      Timeout: 900
      MemorySize: 3008
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: ./index1.zip
      Policies: AWSLambdaFullAccess
      Role: arn:aws:iam::641553134660:role/service-role/demo1
 DeliforceanalyticdriverloggetMethodthree:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: nnnc
      Timeout: 900
      MemorySize: 3008
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: ./index1.zip
      Policies: AWSLambdaFullAccess
      Role: arn:aws:iam::641553134660:role/service-role/demo1
 DeliforceanalyticdriverloggetMethodfour:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: nnnnd
      Timeout: 900
      MemorySize: 3008
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: ./index1.zip
      Policies: AWSLambdaFullAccess
      Role: arn:aws:iam::641553134660:role/service-role/demo1
 DeliforceanalyticdriverloggetMethodfive:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: nnne
      Timeout: 900
      MemorySize: 3008
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: ./index1.zip
      Policies: AWSLambdaFullAccess
      Role: arn:aws:iam::641553134660:role/service-role/demo1
